import { Card, CardHeader, CardTitle } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Download, Eye } from "lucide-react";
import type { Report } from "@/lib/types";

export function ReportTable({
  reports,
  onPreview,
  onDownload,
}: {
  reports: Report[];
  onPreview: (id: string) => void;
  onDownload: (report: Report) => void;
}) {
  return (
    <Card className="p-5">
      <CardHeader>
        <CardTitle>Recent Reports</CardTitle>
      </CardHeader>
      <div className="overflow-x-auto -mx-1">
        <table className="w-full text-sm">
          <thead>
            <tr className="text-left text-[11px] uppercase tracking-wide text-slate-400">
              <th className="font-medium px-2 pb-2">Report ID</th>
              <th className="font-medium px-2 pb-2">Type</th>
              <th className="font-medium px-2 pb-2">Date</th>
              <th className="font-medium px-2 pb-2">Scope</th>
              <th className="font-medium px-2 pb-2">Generated By</th>
              <th className="font-medium px-2 pb-2">Format</th>
              <th className="font-medium px-2 pb-2">Status</th>
              <th className="font-medium px-2 pb-2 text-right">Action</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((r) => (
              <tr key={r.id} className="border-t border-border hover:bg-slate-50 dark:hover:bg-slate-800/50">
                <td className="px-2 py-2.5 font-medium text-slate-700 dark:text-slate-200 whitespace-nowrap">{r.id}</td>
                <td className="px-2 py-2.5 text-slate-600 dark:text-slate-300 whitespace-nowrap">{r.typeLabel}</td>
                <td className="px-2 py-2.5 text-slate-500 dark:text-slate-400 whitespace-nowrap">
                  {new Date(r.createdAt).toLocaleDateString("en-US", { day: "2-digit", month: "short", year: "numeric" })}
                </td>
                <td className="px-2 py-2.5 text-slate-500 dark:text-slate-400 whitespace-nowrap">{r.scope}</td>
                <td className="px-2 py-2.5 text-slate-500 dark:text-slate-400 whitespace-nowrap">{r.generatedBy}</td>
                <td className="px-2 py-2.5"><Badge className="bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 uppercase">{r.format}</Badge></td>
                <td className="px-2 py-2.5">
                  <Badge className={r.status === "ready" ? "bg-green-50 text-green-700 dark:bg-green-500/10 dark:text-green-400" : "bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-400"}>
                    {r.status === "ready" ? "Ready" : "Generating"}
                  </Badge>
                </td>
                <td className="px-2 py-2.5 text-right whitespace-nowrap">
                  <Button variant="ghost" size="sm" onClick={() => onPreview(r.id)}>
                    <Eye size={13} />
                  </Button>
                  <Button variant="ghost" size="sm" onClick={() => onDownload(r)}>
                    <Download size={13} />
                  </Button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Card>
  );
}
